name: CI/CD for Joomla Modules

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: composer install
# ready
      - name: Run PHP Code Beautifier and Fixer (phpcbf)
        run: vendor/bin/phpcbf --standard=phpcs.xml modules/
# ready
     - name: Run PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml modules/
# ready
      - name: Run PHP Mess Detector
        run: vendor/bin/phpmd modules/ text cleancode,codesize,unusedcode,naming,phpmd.xml

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
